#### Exploring Numpy

Numpy package is used to manipulate large arrays and matrices of numeric data.

In [2]:
# importing numpy
import numpy as np

**Creating an array using numpy**

syntax: np.array([list], datatype)

    - np => module name for numpy
    - [list] => list of elements
    - datatype => datatype of the elements

In [8]:
intList = np.array([24, 13, 56, 1], int)
floatList = np.array([24, 13, 56, 1], float)
strList = np.array([24, 13, 56, 1], str)

# display
print(intList)
print(floatList)
print(strList)

[24 13 56  1]
[24. 13. 56.  1.]
['24' '13' '56' '1']


**Slicing an array**

syntax: array[startingIndex:]

this will slice from the *startingIndex* and beyond

In [14]:
arrayList = np.array([12, 45, 23, 1, 90]) # if there is no datatype,  int is default
slicedArray = arrayList[3:]

# display
print(arrayList)
print(slicedArray)

[12 45 23  1 90]
[ 1 90]


**N-Dimensional Arrays**

In [21]:
nDimensionalArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(nDimensionalArray)

# accessing a row
print('row[1]: ', nDimensionalArray[1])

# accessing an element
print('row[2] col[1]: ', nDimensionalArray[2, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
row[1]:  [4 5 6]
row[2] col[1]:  8


**Slicing an N-Dimensional Array**

In [26]:
print('Row 1 and beyond: ', nDimensionalArray[1:]) # prints row 1 and beyond
print('Row 2, Col 1, and beyond: ', nDimensionalArray[2:, 1:]) # prints row 2 and column 1 and beyond

Row 1 and beyond:  [[4 5 6]
 [7 8 9]]
Row 2, Col 1, and beyond:  [[8 9]]


**Checking if a specific element is present in the array**

syntax: elementValue *in* arrayName

In [30]:
print(8 in nDimensionalArray)
print(8 in nDimensionalArray[1])

True
False


**Reshaping array into a new dimension**

syntax: array.reshape((*rowSize*, *colSize*))

In [23]:
import numpy as np

# N-dimensional arrays should have the same number of columns
nDimensionalArray = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])

reshapedArray = nDimensionalArray.reshape((3, 4))

print(reshapedArray)

reshapedArray = nDimensionalArray.reshape((2, 6))

print(reshapedArray)

reshapedArray = nDimensionalArray.reshape((6, 2))

print(reshapedArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


**Transposing an array**

In [24]:
print(reshapedArray.transpose())

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


**Concatenating arrays**

By default, it will concantenate in the rows

In [5]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
array3 = np.concatenate((array1, array2))

print(array3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


You can also specify the axis of which the multiple array will concatenate.

syntax: np.concatenate((*arrays*), axis=n)
where n: 

    0 => vertically (add rows)

    1 => horizontally (add columns)

In [9]:
import numpy as np

# arrays can only be concatenated if and only if both arrays have the same dimesnions
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# concatenate vertically
rowCat = np.concatenate((array1, array2), axis=0)
# concatenate horizontally
colCat = np.concatenate((array1, array2), axis=1)

# display
print('\nAdding vertically: \n', rowCat)
print('\nAdding horizontally: \n', colCat)


Adding vertically: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Adding horizontally: 
 [[1 2 5 6]
 [3 4 7 8]]


**Creating arrays using *arrange***

syntax: np.arange([start, ], stop, [step, ]. dtype=None)

*start* (optional)

    - first value of array(inclusive)
    - default = 0

*stop* (mandatory)

    - end value of array (exclusive)

*step* (optional)

    - increment/decrement between the values in the array
    - default = 1

*dtype* (optional)

    - type of elements of the output array
    - default = None

In [16]:
import numpy as np

array = np.arange(start=24, stop=11, step=-3, dtype=int)

print(array)

[24 21 18 15 12]


**Creating arrays of *ones* and *zeros***

np.ones(shape, dtype=None)

np.zeros(shape, dtype=float)

where:

*shape* - dimension of the array (3, 2)

In [20]:
import numpy as np

ones = np.ones((2, 5), dtype=float) # default is None
zeros = np.zeros((3, 4), dtype=int) # defaalt is float

print(ones)
print(zeros)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


**Creating identity matrix**

Identity matix is a nxn dimensional matrix having *1* on the *main diagonal* and *0*s *elsewhere*

syntax: np.identity(n, dtype=None)

In [26]:
import numpy as np

identity = np.identity(5)

print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Array Mathematics**

operation with a *constant* to every element in the array

In [30]:
import numpy as np

print(np.array([4, 2, 7]) + 5) # addition
print(np.array([4, 2, 7]) - 2) # subtraction
print(np.array([4, 2, 7]) * 3) # multiplication
print(np.array([4, 2, 7]) / 2) # division (automatically converts to float)

[ 9  7 12]
[2 0 5]
[12  6 21]
[2.  1.  3.5]


operation between arrays

In [34]:
import numpy as np

array1 = np.array([[12, 24, 36], [48, 60, 72]])
array2 = np.array([2, 3, 4])
array3 = np.array([[6, 4, 2], [4, 3, 12]])

print(array1 * array2)
print(array1 / array3)

[[ 24  72 144]
 [ 96 180 288]]
[[ 2.  6. 18.]
 [12. 20.  6.]]


some other mathematical functions

In [35]:
array = np.array([-9, 25, 16])

print('\nAbsolute Value: ', np.abs(array))
print('\nSign: ', np.sign(array))
print('\nSquareoot Value: ', np.sqrt(array))
print('\nNatural Logarithm: ', np.log(array))
print('\nLog base 10: ', np.log10(array))
print('\nSine Value: ', np.sin(array))
print('\nCosine Value: ', np.cos(array))


Absolute Value:  [ 9 25 16]

Sign:  [-1  1  1]

Squareoot Value:  [nan  5.  4.]

Natural Logarithm:  [       nan 3.21887582 2.77258872]

Log base 10:  [       nan 1.39794001 1.20411998]

Sine Value:  [-0.41211849 -0.13235175 -0.28790332]

Cosine Value:  [-0.91113026  0.99120281 -0.95765948]


C:\Users\monza\AppData\Local\Temp\ipykernel_16416\3839021491.py:5: RuntimeWarning: invalid value encountered in sqrt
  print('\nSquareoot Value: ', np.sqrt(array))
C:\Users\monza\AppData\Local\Temp\ipykernel_16416\3839021491.py:6: RuntimeWarning: invalid value encountered in log
  print('\nNatural Logarithm: ', np.log(array))
C:\Users\monza\AppData\Local\Temp\ipykernel_16416\3839021491.py:7: RuntimeWarning: invalid value encountered in log10
  print('\nLog base 10: ', np.log10(array))


**Rounding off arrays**

In [37]:
import numpy as np

array = np.array([2.5, 2.52, 2.8])

print(np.floor(array)) # round down
print(np.ceil(array))  # round up
print(np.rint(array))  # round to the nearest number

[2. 2. 2.]
[3. 3. 3.]
[2. 3. 3.]


**Pi and Euler's number**

In [38]:
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


**Array iteration**

In [45]:
import numpy as np

numbers = np.array([[12, 24, 36], [48, 60, 72]])

# iterating rows only
for row in numbers:
    print(row)

# iterating each element
for row in numbers:
    for col in row:
        print(col)

# multiple assignments
for (x, y, z) in numbers:
    print('(x, y, z) = ({0}, {1}, {2})'.format(x, y, z))

[12 24 36]
[48 60 72]
12
24
36
48
60
72
(x, y, z) = (12, 24, 36)
(x, y, z) = (48, 60, 72)


**Whole-Array Properties**

In [53]:
import numpy as np

array = np.array([2, 7, 4, 6])

print('\n Sum: ', array.sum())
print('\n Product: ', array.prod())
print('\n Mean: ', array.mean())
print('\n Variance: ', array.var())
print('\n Standard Deviation: ', array.std())
print('\n Minimum Value: ', array.min())
print('\n Maximum Value: ', array.max())
print('\n Index of the minimum value: ', array.argmin())
print('\n Index of the maximum value: ', array.argmax())
print('\n Unique Values: ', np.unique(array))

dArray = np.array([[2, 7, 4, 6], [2, 7, 4, 6]])
print(dArray)
print('\n Diagonal: ', np.diagonal(dArray))


 Sum:  19

 Product:  336

 Mean:  4.75

 Variance:  3.6875

 Standard Deviation:  1.920286436967152

 Minimum Value:  2

 Maximum Value:  7

 Index of the minimum value:  0

 Index of the maximum value:  1

 Unique Values:  [2 4 6 7]
[[2 7 4 6]
 [2 7 4 6]]

 Diagonal:  [2 7]


**Relational Operators and Value Testing**

In [57]:
import numpy as np

array1 = np.array([[-24, 26, 190], [67, -12, 2]])
array2 = np.array([4, 1, 200])
c = array1 > array2

print(c)
print(np.any(c)) # returns True if atleast 1 True exist
print(np.all(c)) # returns True if and only if all elements are True

[[False  True False]
 [ True False False]]
True
False


**Boolean Exppressions**

In [5]:
import numpy as np

array1 = np.array([1, -2, 45, 13], int)
array2 = np.array([-15, 23, 45, 14], float)

logicAND = np.logical_and(array1 > array2, array1 < array2)
logicNOT = np.logical_not(logicAND)
logicOR = np.logical_or(logicNOT, logicAND)
logicXOR = np.logical_xor(logicOR, logicNOT)

# display
print('Logic AND:', logicAND)
print('Logic NOT:', logicNOT)
print('Logic OR:', logicOR)
print('Logic XOR:', logicXOR)

Logic AND: [False False False False]
Logic NOT: [ True  True  True  True]
Logic OR: [ True  True  True  True]
Logic XOR: [False False False False]


In [13]:
import numpy as np

array = np.identity(5, dtype=int)

# array.nonzero() - returns the tuple of indices of the nonzero values in the array
print(array)
print(array.nonzero())

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
(array([0, 1, 2, 3, 4], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64))


In [16]:
import numpy as np

array = np.array([2, np.nan, 24, -13, np.inf])

print(np.isnan(array))    # check if the element is NaN
print(np.isfinite(array)) # check if the element is finite

[False  True False False False]
[ True False  True  True False]


**Array item selection and manipulation**

Get all the elements in the array that passes the given requirement

In [17]:
import numpy as np 

array = np.array([12, 34, 36, 48])
condition = np.array([5, 12, 6, 4])

print(array[array % condition == 0])

[36 48]


Use another array to act as index to access another array

In [20]:
import numpy as np 

array = np.array([12, 34, 36, 48])
# displays index 3, index 0 , index 2, index 1
index = np.array([3, 0, 2, 1])

print(array[index])

[48 12 36 34]


In [29]:
import numpy as np 

array = np.array([[12, 34, 36, 48], [15, 23, 89, 25]])

# displays row 1, row 0
index = np.array([1, 0])

# display using rows and columns (rows and columns should have the same dimension)
row = np.array([0, 1, 1, 1, 0])
column = np.array([2, 1, 3, 0, 2])

print(array[row, column])

[36 23 25 15 36]


Using *take()* function


In [36]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = [0, 2, 1]

#  display
print('Vertically(row): \n', np.take(array, indices, axis=0))
print('Horizontally(column): \n', np.take(array, indices, axis=1))

Vertically(row): 
 [[1 2 3]
 [7 8 9]
 [4 5 6]]
Horizontally(column): 
 [[1 3 2]
 [4 6 5]
 [7 9 8]]


**More Mathematics**

Dot product


In [41]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([3, 1, 5, 7])

# dot-product of 1D arrays
print(np.dot(a, b)) # (1*3 + 2*1 + 3*5 + 4*7)

a = np.array([[1, 2], [3, 4]])
b = np.array([[3, 1], [5, 7]])

# Matrix Multiplication
print(np.dot(a, b))
# [1*3 + 2*5] [1*1 + 2*7]
# [3*3 + 4*5] [3*1 + 4*7]

48
[[13 15]
 [29 31]]


Outer Product

In [45]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.outer(a, b))
# 1*4   1*5   1*6   
# 2*4   2*5   2*6  
# 3*4   3*5   3*6  

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Inner Product

In [44]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.inner(a, b)) # (1*4) + (2*5) + (3*6)

32


In [47]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([3, 1, 2])

print(np.cross(a, b))
# a = x, y, z
# b = x, y, z
# c = (ay*bz - az*by), (az*bx - ax*bz), (ax*by - ay*bx)

[ 1  7 -5]


**Linear Alegbra Calculations**

syntax: np.linalg.*function()*

In [49]:
import numpy as np

M = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]], int)

detM = np.linalg.det(M)
EvalM, EvecM = np.linalg.eig(M)
invM = np.linalg.inv(M)

print('The determinant of the matrix is:\n',detM)
print('The eigenvalue of the matrix is:\n',EvalM)
print('The eigenvector of the matrix is:\n',EvecM)
print('The inverse of the matrix is:\n',invM)

The determinant of the matrix is:
 -306.0
The eigenvalue of the matrix is:
 [11.24862343  5.09285054 -5.34147398]
The eigenvector of the matrix is:
 [[ 0.24511338  0.75669314  0.02645665]
 [ 0.40622202 -0.03352363 -0.84078293]
 [ 0.88028581 -0.65291014  0.54072554]]
The inverse of the matrix is:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


**Polynomial Mathematics**

You can assign coefficient of the polynomial as elements in an array.

[1,2,3,4] => 𝑥<sup>3</sup> + 2𝑥<sup>2</sup> + 3𝑥 + 4

In [53]:
import numpy as np

poly = np.array([1, 2, -15])

#  return the roots
print('The roots are:\n',np.roots(poly))

# return the integration where the constant of integration is set to 0
print('The coefficients of the integral are:\n',np.polyint(poly))

# returns the derivative
print('The coefficients of the derivative are:\n',np.polyder(poly))

# returns the value, where the value of the independent variable is the parameter passed
print('The value of the polynomial at x=3 is:\n',np.polyval(poly, 3))

The roots are:
 [-5.  3.]
The coefficients of the integral are:
 [  0.33333333   1.         -15.           0.        ]
The coefficients of the derivative are:
 [2 2]
The value of the polynomial at x=3 is:
 0


You can also determine the polynomial coefficients, given a set of roots.

In [54]:
import numpy as np

roots = np.array([-5, 3])

print("The coefficients of the polynomial are:\n", np.poly(roots))

The coefficients of the polynomial are:
 [  1.   2. -15.]


A set of data for x (independent variable) and y (dependent variable) can be fit to a polynomial of specified degree using the *polyfit* function

In [57]:
import numpy as np
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0.2, 2.1, 1.2, 3.4, 6.8, 9.2, 10.9, 19.0]
print(np.polyfit(x, y, 2))

[ 0.38809524 -1.07619048  1.54642857]
