### Laboratory Activity #4

Members:

- Guzman, Jastine
- Monzales, Kathleen Iza
- Tejada, Jay
- Izumi, Sana
- Calzada, Mark David
- Gobui, Ralph Matthew


In [1]:
import numpy as np

1.) Create a python program that will ask the user to input the values the elements of a 3x3 Matrix. Then
store this values in a 2D array. (You don’t have to use the numpy.append for this number)

    a.) Print the diagonal of the matrix

    b.) Print the inverse of the matrix

    c.) Print the determinant of the matrix

In [6]:
# Function to input a 3x3 matrix from the user
def input_matrix():
    matrix = []
    print("Enter the elements of the 3x3 matrix:")
    for i in range(3):
        row = []
        for j in range(3):
            element = float(input(f"Enter element at position ({i}, {j}): "))
            row.append(element)
        matrix.append(row)
    return matrix

def number_one():
    matrix = input_matrix()

    # Convert the 2D list into a numpy array
    np_matrix = np.array(matrix)

    print("Matrix:")
    print(np_matrix)

    # a.) Print the diagonal of the matrix
    diagonal = np.diag(np_matrix)
    print("Diagonal elements:", diagonal)

    # b.) Print the inverse of the matrix
    try:
        inverse = np.linalg.inv(np_matrix)
        print("Inverse matrix:")
        print(inverse)
    except np.linalg.LinAlgError:
        print("The matrix is singular and doesn't have an inverse.")

    # c.) Print the determinant of the matrix
    determinant = np.linalg.det(np_matrix)
    print("Determinant:", determinant)

number_one()

Enter the elements of the 3x3 matrix:
Matrix:
[[ 3.  2. 12.]
 [34. 43. 23.]
 [64. 24. 65.]]
Diagonal elements: [ 3. 43. 65.]
Inverse matrix:
[[-0.12475666 -0.00878803  0.02614161]
 [ 0.04104789  0.03187052 -0.01885533]
 [ 0.10768118 -0.00311474 -0.00339285]]
Determinant: -17979.0


2.) Create a python program that will ask the user the degree of the polynomial and the values of the
coefficients of the polynomial. Store the values of the component using numpy.append (Note you can
use numpy.array([]) to create an empty array.) The print the following:

    a. The roots of the polynomial

    b. The derivative of the polynomial

    c. The integration of the polynomial


In [7]:
# Function to input coefficients from the user
def input_coefficients(degree):
    # empty
    poly = np.array([])

    for i in range(degree + 1):
        coefficient = float(input(f"Enter coefficient for x^{i}: "))
        poly = np.append(poly, coefficient)
    
    return poly

def number_two():
    degree = int(input("Enter the degree: "))
    print(degree)

    poly = input_coefficients(degree)

    # a.) Print the roots of the polynomial
    roots = np.roots(poly)
    print("The roots are: ", roots)

    # b.) Print the derivative of the polynomial
    derivative = np.polyder(poly)
    print("The coefficients of the derivative are: ", derivative)

    # c.) Print the integration of the polynomial
    integration = np.polyint(poly)
    print("The coefficients of the integral are: ", integration)

number_two()

2
The roots are:  [-0.17751743  0.1310058 ]
The coefficients of the derivative are:  [86.  2.]
The coefficients of the integral are:  [14.33333333  1.         -1.          0.        ]


3.) Create a python program that will ask the user to input the components of two vectors (Store the
values of the component using numpy.append). Then calculate the following:

    a. The dot product of the two vectors.

    b. The cross product of the two vectors.

    c. The magnitude of the cross product.

In [10]:
def input_matrix():
    matrix = []
    print("Enter the elements of the 3x3 matrix:")
    for i in range(3):
        row = []
        for j in range(3):
            element = float(input(f"Enter element at position ({i}, {j}): "))
            row.append(element)
        matrix.append(row)
    return matrix

def number_three():
    vectorA = input_matrix()
    vectorB = input_matrix()

    # a.) Print the dot product of the two vectors
    dot = np.dot(vectorA, vectorB)
    print("Dot product: \n", dot)

    # b.) Print the cross product of the two vectors
    cross = np.cross(vectorA, vectorB)
    print("Cross Product: \n", cross)

    # c.) Print the magnitude of the cross product
    magnitude = np.linalg.norm(cross)
    print("Magnitude of the Cross Product: \n", magnitude)

number_three()

Enter the elements of the 3x3 matrix:
Enter the elements of the 3x3 matrix:
Dot product: 
 [[12. 18.  9.]
 [12. 18.  7.]
 [12. 18.  9.]]
Cross Product: 
 [[-7.  5. -1.]
 [ 0.  0.  0.]
 [-5.  4. -1.]]
Magnitude of the Cross Product: 
 10.816653826391969


4.) Create a python program that will ask the user to input 10 floating-point number then store it in a 1D
array using numpy.append. Calculate and print the following:

    a.) The mean value of the elements in the array.

    b.) Print the elements that are greater than 2.

    c.) Print the first five highest values in the array in descending order (Hint: read more about sorted
    function).

In [15]:
def number_four():
    array = []

    # input 10 floating points
    for i in range(10):
        x = float(input(f"Enter a floating-point number[{i + 1}]: "))
        array = np.append(array, x)
    
    # a.) Print the mean
    mean = array.mean()
    print("Mean of the array: ", mean)

    # b.) Print all elements that are greater than 2
    arrayGreaterThan2 = array[array > 2]
    print("Elements that are greater than 2: ", arrayGreaterThan2)

    # c.) Print the first five highest values in descending order
    descendingOrder = sorted(array, reverse=True)
    slicedArray = descendingOrder[:5]
    print("The First Five Highest Elements: ", slicedArray)

number_four()

Mean of the array:  22.6
Elements that are greater than 2:  [12. 34. 34. 89. 34. 56. 24.]
The First Five Highest Elements:  [89.0, 56.0, 34.0, 34.0, 34.0]
